name: llm-cooperation
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.11
  - blackd
  - evals
  - ipython
  - jupyter
  - jupytext
  - jupyter-book
  - nbconvert
  - openai
  - pandas
  - pandas-stubs
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - pytest-lazy-fixture
  - mypy
  - pylint
  - pre-commit
  - plotly
  - python-kaleido
  - pyppeteer
  - pingouin
  - qtconsole
  - r-base
  - r-bh
  - r-brms
  - r-tidyverse
  - r-ggpubr
  - r-lme4
  - r-matrix=1.6.0
  - r-rstatix
  - r-tmb=1.9.6
  - r-glmmTMB
  - r-geepack
  - r-reticulate
  - r-irkernel
  - r-dharma
  - r-stargazer
  - r-modelsummary
  - r-texreg
  - r-MCMCglmm
  - r-effects
  - r-sjPlot
  - r-patchwork
  - r-R.cache
  - r-cmdstanr
  - r-languageserver
  - pip
  - pip:
    - -e ./
    - openai-pygenerator>=0.6.2
