name: llm-cooperation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipython
  - jupyter
  - nbconvert
  - openai
  - pandas
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - mypy
  - pre-commit
  - pip
  - pip:
    - -e ./
