name: llm-cooperation
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - blackd
  - evals
  - ipython
  - jupyter
  - jupytext
  - jupyter-book
  - nbconvert
  - openai
  - pandas
  - pandas-stubs
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - mypy
  - pylint
  - pre-commit
  - plotly
  - pyppeteer
  - pip
  - pip:
    - -e ./
    - openai-pygenerator
