name: llm-cooperation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - blackd
  - ipython
  - jupyter
  - jupytext
  - jupyter-book
  - nbconvert
  - openai
  - pandas
  - pandas-stubs
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - mypy
  - pylint
  - pre-commit
  - pyppeteer
  - pip
  - pip:
    - -e ./
