name: llm-cooperation
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.11
  - blackd
  - evals
  - ipython
  - jupyter
  - jupytext
  - jupyter-book
  - nbconvert
  - openai
  - pandas
  - pandas-stubs
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - pytest-lazy-fixture
  - mypy
  - pylint
  - pre-commit
  - plotly
  - python-kaleido
  - pyppeteer
  - pingouin
  - r-base
  - r-tidyverse
  - r-ggpubr
  - r-lme4
  - r-matrix>=1.6.2
  - r-rstatix
  - r-glmmTMB
  - r-reticulate
  - r-irkernel
  - pip
  - pip:
    - -e ./
    - openai-pygenerator>=0.6.2
