# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Investigating Emergent Goal-Like Behavior in Large Language Models using Experimental Economics
author: <a href="https://sphelps.net/">Steve Phelps</a> and <a href="https://www.mdx.ac.uk/about-us/our-people/staff-directory/profile/russell-yvan">Yvan I. Russell</a>
date: 3/6/2023
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: llm-cooperation.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - llm-cooperation.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/phelps-sg/llm-cooperation
  path_to_book: jupyter-book # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    bibtex_reference_style: author_year

html_theme_options:
  theme_color_mode: "light"
